#!/usr/bin/env bash
# Build the release APK inside the Linux container.
#
# Why not `eas build --local`: it refuses to run on Windows ("Unsupported platform,
# macOS or Linux is required"). Running the same steps in a Linux container sidesteps
# both that and the MAX_PATH problem, because the project lives at /app.
set -euo pipefail
cd /app

echo "=== environment ==="
echo "node      $(node -v)"
echo "java      $(java -version 2>&1 | head -1)"
echo "ANDROID_HOME=${ANDROID_HOME}"
echo "NDK       $(ls /opt/android-sdk/ndk | head -1)"
echo "EXPO_PUBLIC_SUPABASE_URL set: $([ -n "${EXPO_PUBLIC_SUPABASE_URL:-}" ] && echo yes || echo NO)"
echo "EXPO_PUBLIC_SUPABASE_ANON_KEY set: $([ -n "${EXPO_PUBLIC_SUPABASE_ANON_KEY:-}" ] && echo yes || echo NO)"
echo

echo "=== prebuild (regenerates android/) ==="
rm -rf android
npx expo prebuild --platform android --no-install
echo "prebuild done"
echo

echo "=== signing config generated by prebuild ==="
grep -n -A 12 'signingConfigs' android/app/build.gradle | head -25
echo

echo "=== gradle assembleRelease ==="
cd android
./gradlew assembleRelease --no-daemon

echo
echo "=== output ==="
find /app/android -name '*.apk' -exec ls -la {} \;
