import AsyncStorage from '@react-native-async-storage/async-storage';
import type { JobRow } from '../types';

/**
 * Local persistence.
 *
 * Everything here is device state, not source of truth — the database owns the
 * jobs. The cache exists so the list renders instantly on cold start and still
 * shows something when the network is down.
 */

const KEYS = {
  lastOpenedAt: 'applyez.lastOpenedAt',
  cachedJobs: 'applyez.cachedJobs',
  cacheAt: 'applyez.cacheAt',
  deviceId: 'applyez.deviceId',
  pushToken: 'applyez.pushToken',
  pushEnabled: 'applyez.pushEnabled',
  resumeSelection: 'applyez.resumeSelection',
  minRelevance: 'applyez.minRelevance',
  showFiltered: 'applyez.showFiltered',
} as const;

export type ResumeSlot = 'tech' | 'data' | 'general';
export type ResumeSelection = Partial<Record<ResumeSlot, string>>;

async function getString(key: string): Promise<string | null> {
  try {
    return await AsyncStorage.getItem(key);
  } catch {
    // A storage failure must never take down a screen.
    return null;
  }
}

async function setString(key: string, value: string): Promise<void> {
  try {
    await AsyncStorage.setItem(key, value);
  } catch {
    /* ignore */
  }
}

/**
 * The timestamp used to decide which jobs are "new".
 *
 * Deliberately separate from `cacheAt`: refreshing the cache must not clear the
 * new-job badge, and opening the app must not invalidate the cache.
 */
export async function getLastOpenedAt(): Promise<number | null> {
  const raw = await getString(KEYS.lastOpenedAt);
  if (!raw) return null;
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? parsed : null;
}

export async function setLastOpenedAt(value: number): Promise<void> {
  await setString(KEYS.lastOpenedAt, String(value));
}

/**
 * Raw rows are cached, not the mapped view.
 *
 * Caching the view would bake in an `isNew` flag computed against whatever the
 * baseline happened to be when the cache was written, so a cold start would show
 * stale NEW badges. Caching the rows lets both the cache and the network go
 * through `toJobView` with the current session's baseline.
 */
export async function getCachedJobs(): Promise<{ rows: JobRow[]; at: number } | null> {
  const [rowsRaw, atRaw] = await Promise.all([
    getString(KEYS.cachedJobs),
    getString(KEYS.cacheAt),
  ]);
  if (!rowsRaw) return null;
  try {
    const rows = JSON.parse(rowsRaw) as JobRow[];
    const at = atRaw ? Number(atRaw) : 0;
    return { rows: Array.isArray(rows) ? rows : [], at: Number.isFinite(at) ? at : 0 };
  } catch {
    return null;
  }
}

export async function setCachedJobs(rows: JobRow[]): Promise<void> {
  await Promise.all([
    setString(KEYS.cachedJobs, JSON.stringify(rows)),
    setString(KEYS.cacheAt, String(Date.now())),
  ]);
}

/**
 * A stable per-install id.
 *
 * Used to key the push token row. Not a device identifier — it is generated by us
 * and dies with the install, which is all we need to tell two phones apart.
 */
export async function getDeviceId(): Promise<string> {
  const existing = await getString(KEYS.deviceId);
  if (existing) return existing;
  const generated = `dev_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 10)}`;
  await setString(KEYS.deviceId, generated);
  return generated;
}

export async function getStoredPushToken(): Promise<string | null> {
  return getString(KEYS.pushToken);
}

export async function setStoredPushToken(token: string | null): Promise<void> {
  if (token === null) {
    try {
      await AsyncStorage.removeItem(KEYS.pushToken);
    } catch {
      /* ignore */
    }
    return;
  }
  await setString(KEYS.pushToken, token);
}

export async function getPushEnabled(): Promise<boolean> {
  return (await getString(KEYS.pushEnabled)) !== 'false';
}

export async function setPushEnabled(enabled: boolean): Promise<void> {
  await setString(KEYS.pushEnabled, enabled ? 'true' : 'false');
}

export async function getResumeSelection(): Promise<ResumeSelection> {
  const raw = await getString(KEYS.resumeSelection);
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw) as ResumeSelection;
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
}

export async function setResumeSelection(selection: ResumeSelection): Promise<void> {
  await setString(KEYS.resumeSelection, JSON.stringify(selection));
}

/**
 * Relevance display threshold.
 *
 * The scraper computes a 0-100 score; this is the cut-off below which the list
 * hides a job. It lives on the device rather than in the scraper so it can be tuned
 * without re-scraping the whole backlog — the score is a measurement, the threshold
 * is a preference.
 */
export async function getMinRelevance(fallback: number): Promise<number> {
  const raw = await getString(KEYS.minRelevance);
  if (!raw) return fallback;
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? parsed : fallback;
}

export async function setMinRelevance(value: number): Promise<void> {
  await setString(KEYS.minRelevance, String(value));
}

/** When true, jobs below the threshold are listed too (dimmed, not hidden). */
export async function getShowFiltered(): Promise<boolean> {
  return (await getString(KEYS.showFiltered)) === 'true';
}

export async function setShowFiltered(value: boolean): Promise<void> {
  await setString(KEYS.showFiltered, value ? 'true' : 'false');
}

export async function clearCache(): Promise<void> {
  try {
    await AsyncStorage.multiRemove([KEYS.cachedJobs, KEYS.cacheAt]);
  } catch {
    /* ignore */
  }
}
