/// <reference types="expo/types" />

// Generated by Expo, and committed on purpose despite what `apps/mobile/.gitignore`
// says: `npm run typecheck` has to work on a fresh clone without running the dev
// server first. Expo rewrites this file (and re-appends the ignore rule) whenever
// the dev server starts, so treat the note below as noise.
//
// NOTE: This file should not be edited and should be in your git ignore